version: "2"

linters:
  default: none
  enable:
    - govet
    - staticcheck
    - revive
    - errcheck
    - unused
    - gocyclo
  disable:
    - funlen
    - wsl
  exclusions:
    rules:
      # ignore ST1023 only inside client_test.go since we want to show the types explicitly to help users understand the code
      # ST1023: should omit type T from declaration; it will be inferred from the right-hand side 
      # QF1011: could omit type T from declaration; it will be inferred from the right-hand side 
      - path: _test\.go$
        linters:
          - staticcheck
        text: "^(ST1023|QF1011):"
      # ignore dot-imports only inside _test.go since we use dot imports for ginkgo and gomega
      - path: _test\.go$
        linters:
          - revive
        text: 'dot-imports: should not use dot imports'

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
      rewrite-rules:
        - pattern: 'interface{}'
          replacement: 'any'
        - pattern: 'a[b:len(a)]'
          replacement: 'a[b:]'

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

